/**
 * Auth Relations
 *
 * Relations for tables in auth.ts (which is auto-generated by better-auth).
 * This file is manually maintained and defines application-specific relations.
 */

import { relations } from 'drizzle-orm';
import { aiActionItems, aiTopics } from './ai-insights';
import {
  accounts,
  apikeys,
  invitations,
  members,
  oauthAccessTokens,
  oauthClients,
  oauthConsents,
  oauthRefreshTokens,
  organizations,
  passkeys,
  sessions,
  subscriptions,
  twoFactors,
  users,
} from './auth';
import { invoices, paymentMethods, usage } from './billing';
import { decisions, knowledgeNodes } from './knowledge';
import { notifications } from './notifications';
import { userExtensions, userPreferences } from './user-extensions';
import { channels, collections, videoProgresses, videos } from './videos';

// =============================================================================
// User Relations
// =============================================================================

export const userRelations = relations(users, ({ one, many }) => ({
  sessions: many(sessions),
  accounts: many(accounts),
  members: many(members),
  invitations: many(invitations),
  twoFactor: one(twoFactors),
  passkeys: many(passkeys),
  apiKeys: many(apikeys),
  preferences: one(userPreferences),
  extensions: one(userExtensions),
  // Application relations
  videos: many(videos),
  videoProgresses: many(videoProgresses),
  // Notification relations (must match relationName from notificationRelations)
  notifications: many(notifications, { relationName: 'NotificationRecipient' }),
  actedNotifications: many(notifications, { relationName: 'NotificationActor' }),
}));

// =============================================================================
// Session Relations
// =============================================================================

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, {
    fields: [sessions.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// Account Relations
// =============================================================================

export const accountsRelations = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// Organization Relations
// =============================================================================

export const organizationRelations = relations(organizations, ({ one, many }) => ({
  members: many(members),
  invitations: many(invitations),
  videos: many(videos),
  channels: many(channels),
  collections: many(collections),
  subscription: one(subscriptions),
  usageRecords: many(usage),
  invoices: many(invoices),
  paymentMethods: many(paymentMethods),
  decisions: many(decisions),
  knowledgeNodes: many(knowledgeNodes),
  aiTopics: many(aiTopics),
  aiActionItems: many(aiActionItems),
}));

// =============================================================================
// Member Relations
// =============================================================================

export const membersRelations = relations(members, ({ one }) => ({
  organization: one(organizations, {
    fields: [members.organizationId],
    references: [organizations.id],
  }),
  user: one(users, {
    fields: [members.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// Invitation Relations
// =============================================================================

export const invitationsRelations = relations(invitations, ({ one }) => ({
  organization: one(organizations, {
    fields: [invitations.organizationId],
    references: [organizations.id],
  }),
  inviter: one(users, {
    fields: [invitations.inviterId],
    references: [users.id],
  }),
}));

// =============================================================================
// Subscription Relations
// =============================================================================

export const subscriptionsRelations = relations(subscriptions, ({ one }) => ({
  organization: one(organizations, {
    // better-auth uses referenceId to link subscriptions to organizations
    fields: [subscriptions.referenceId],
    references: [organizations.id],
  }),
}));

// =============================================================================
// Two-Factor Relations
// =============================================================================

export const twoFactorRelations = relations(twoFactors, ({ one }) => ({
  user: one(users, {
    fields: [twoFactors.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// Passkey Relations
// =============================================================================

export const passkeyRelations = relations(passkeys, ({ one }) => ({
  user: one(users, {
    fields: [passkeys.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// API Key Relations
// =============================================================================

export const apiKeyRelations = relations(apikeys, ({ one }) => ({
  user: one(users, {
    fields: [apikeys.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// OAuth Client Relations
// =============================================================================

export const oauthClientsRelations = relations(oauthClients, ({ one, many }) => ({
  user: one(users, {
    fields: [oauthClients.userId],
    references: [users.id],
  }),
  accessTokens: many(oauthAccessTokens),
  refreshTokens: many(oauthRefreshTokens),
  consents: many(oauthConsents),
}));

// =============================================================================
// OAuth Refresh Token Relations
// =============================================================================

export const oauthRefreshTokensRelations = relations(oauthRefreshTokens, ({ one }) => ({
  client: one(oauthClients, {
    fields: [oauthRefreshTokens.clientId],
    references: [oauthClients.id],
  }),
  session: one(sessions, {
    fields: [oauthRefreshTokens.sessionId],
    references: [sessions.id],
  }),
  user: one(users, {
    fields: [oauthRefreshTokens.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// OAuth Access Token Relations
// =============================================================================

export const oauthAccessTokensRelations = relations(oauthAccessTokens, ({ one }) => ({
  client: one(oauthClients, {
    fields: [oauthAccessTokens.clientId],
    references: [oauthClients.id],
  }),
  session: one(sessions, {
    fields: [oauthAccessTokens.sessionId],
    references: [sessions.id],
  }),
  refreshToken: one(oauthRefreshTokens, {
    fields: [oauthAccessTokens.refreshId],
    references: [oauthRefreshTokens.id],
  }),
  user: one(users, {
    fields: [oauthAccessTokens.userId],
    references: [users.id],
  }),
}));

// =============================================================================
// OAuth Consent Relations
// =============================================================================

export const oauthConsentsRelations = relations(oauthConsents, ({ one }) => ({
  user: one(users, {
    fields: [oauthConsents.userId],
    references: [users.id],
  }),
  client: one(oauthClients, {
    fields: [oauthConsents.clientId],
    references: [oauthClients.id],
  }),
}));
