/**
 * Schema Type Exports
 *
 * Centralized type exports derived from schema tables and enums.
 * This file provides TypeScript types for use throughout the application.
 */

// =============================================================================
// Auth Table Types (from auth.ts - auto-generated by better-auth)
// =============================================================================

import type {
  accounts,
  apikeys,
  invitations,
  members,
  oauthAccessTokens,
  oauthClients,
  oauthConsents,
  oauthRefreshTokens,
  organizationRoles as organizationRolesTable,
  organizations,
  passkeys,
  sessions,
  ssoProviders,
  subscriptions,
  twoFactors,
  users,
  verifications,
} from './auth';

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;
export type Verification = typeof verifications.$inferSelect;
export type NewVerification = typeof verifications.$inferInsert;
export type Organization = typeof organizations.$inferSelect;
export type NewOrganization = typeof organizations.$inferInsert;
export type Member = typeof members.$inferSelect;
export type NewMember = typeof members.$inferInsert;
export type Invitation = typeof invitations.$inferSelect;
export type NewInvitation = typeof invitations.$inferInsert;
export type TwoFactor = typeof twoFactors.$inferSelect;
export type NewTwoFactor = typeof twoFactors.$inferInsert;
export type Passkey = typeof passkeys.$inferSelect;
export type NewPasskey = typeof passkeys.$inferInsert;
export type ApiKey = typeof apikeys.$inferSelect;
export type NewApiKey = typeof apikeys.$inferInsert;
export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;
export type OAuthClient = typeof oauthClients.$inferSelect;
export type NewOAuthClient = typeof oauthClients.$inferInsert;
export type OAuthRefreshToken = typeof oauthRefreshTokens.$inferSelect;
export type NewOAuthRefreshToken = typeof oauthRefreshTokens.$inferInsert;
export type OAuthAccessToken = typeof oauthAccessTokens.$inferSelect;
export type NewOAuthAccessToken = typeof oauthAccessTokens.$inferInsert;
export type OAuthConsent = typeof oauthConsents.$inferSelect;
export type NewOAuthConsent = typeof oauthConsents.$inferInsert;
export type OrganizationRoleRow = typeof organizationRolesTable.$inferSelect;
export type NewOrganizationRoleRow = typeof organizationRolesTable.$inferInsert;
export type SsoProvider = typeof ssoProviders.$inferSelect;
export type NewSsoProvider = typeof ssoProviders.$inferInsert;

// =============================================================================
// Enum Value Types (derived from pgEnum definitions)
// =============================================================================

import type {
  actionItemPriorityEnum,
  actionItemStatusEnum,
  activityTypeEnum,
  auditLogCategoryEnum,
  auditLogSeverityEnum,
  clipStatusEnum,
  clipTypeEnum,
  codeLinkTypeEnum,
  consentActionEnum,
  decisionStatusEnum,
  decisionTypeEnum,
  healthCheckServiceEnum,
  healthCheckStatusEnum,
  highlightReelStatusEnum,
  importStatusEnum,
  integrationProviderEnum,
  invoiceStatusEnum,
  knowledgeNodeTypeEnum,
  legalDocumentTypeEnum,
  momentTypeEnum,
  notificationTypeEnum,
  organizationRoleEnum,
  participantRoleEnum,
  processingStatusEnum,
  reactionTypeEnum,
  reportCategoryEnum,
  reportResolutionEnum,
  reportResourceTypeEnum,
  reportStatusEnum,
  subscriptionStatusEnum,
  topicTrendEnum,
  userRoleEnum,
  videoShareLinkAccessEnum,
  videoShareLinkStatusEnum,
  videoViewSourceEnum,
  workflowTemplateTypeEnum,
  zapierWebhookEventEnum,
} from './enums';

// Auth enums
export type UserRole = (typeof userRoleEnum.enumValues)[number];
export type OrganizationRole = (typeof organizationRoleEnum.enumValues)[number];

// Video processing enums
export type ProcessingStatus = (typeof processingStatusEnum.enumValues)[number];

// Comment & reaction enums
export type ReactionType = (typeof reactionTypeEnum.enumValues)[number];

// Notification enums
export type NotificationType = (typeof notificationTypeEnum.enumValues)[number];

// Integration enums
export type IntegrationProvider = (typeof integrationProviderEnum.enumValues)[number];
export type ImportStatus = (typeof importStatusEnum.enumValues)[number];

// Code link enums
export type CodeLinkType = (typeof codeLinkTypeEnum.enumValues)[number];

// Billing enums
export type SubscriptionStatus = (typeof subscriptionStatusEnum.enumValues)[number];
export type InvoiceStatus = (typeof invoiceStatusEnum.enumValues)[number];

// Knowledge graph enums
export type DecisionStatus = (typeof decisionStatusEnum.enumValues)[number];
export type ParticipantRole = (typeof participantRoleEnum.enumValues)[number];
export type KnowledgeNodeType = (typeof knowledgeNodeTypeEnum.enumValues)[number];
export type DecisionType = (typeof decisionTypeEnum.enumValues)[number];

// AI insights enums
export type TopicTrend = (typeof topicTrendEnum.enumValues)[number];
export type ActionItemStatus = (typeof actionItemStatusEnum.enumValues)[number];
export type ActionItemPriority = (typeof actionItemPriorityEnum.enumValues)[number];

// Legal enums
export type LegalDocumentType = (typeof legalDocumentTypeEnum.enumValues)[number];
export type ConsentAction = (typeof consentActionEnum.enumValues)[number];
export type ReportCategory = (typeof reportCategoryEnum.enumValues)[number];
export type ReportStatus = (typeof reportStatusEnum.enumValues)[number];
export type ReportResolution = (typeof reportResolutionEnum.enumValues)[number];
export type ReportResourceType = (typeof reportResourceTypeEnum.enumValues)[number];

// Audit log enums
export type AuditLogCategory = (typeof auditLogCategoryEnum.enumValues)[number];
export type AuditLogSeverity = (typeof auditLogSeverityEnum.enumValues)[number];

// Video analytics enums
export type VideoViewSource = (typeof videoViewSourceEnum.enumValues)[number];

// Video sharing enums
export type VideoShareLinkStatus = (typeof videoShareLinkStatusEnum.enumValues)[number];
export type VideoShareLinkAccess = (typeof videoShareLinkAccessEnum.enumValues)[number];

// Workflow template enums
export type WorkflowTemplateType = (typeof workflowTemplateTypeEnum.enumValues)[number];

// Video clips enums
export type ClipType = (typeof clipTypeEnum.enumValues)[number];
export type MomentType = (typeof momentTypeEnum.enumValues)[number];
export type ClipStatus = (typeof clipStatusEnum.enumValues)[number];
export type HighlightReelStatus = (typeof highlightReelStatusEnum.enumValues)[number];

// Health check enums
export type HealthCheckService = (typeof healthCheckServiceEnum.enumValues)[number];
export type HealthCheckStatus = (typeof healthCheckStatusEnum.enumValues)[number];

// Activity feed enums
export type ActivityType = (typeof activityTypeEnum.enumValues)[number];
export type ZapierWebhookEvent = (typeof zapierWebhookEventEnum.enumValues)[number];
