catalogMode: strict
cleanupUnusedCatalogs: true

catalog:
  # AI SDK
  "@ai-sdk/gateway": 3.0.2
  "@ai-sdk/react": 3.0.3
  ai: 6.0.3

  # AWS SDK
  "@aws-sdk/client-s3": 3.958.0
  "@aws-sdk/lib-storage": 3.958.0
  "@aws-sdk/s3-request-presigner": 3.958.0

  # Effect
  "@effect/platform": 0.94.0
  "@effect/platform-node": 0.104.0
  "@effect/schema": 0.75.5
  "@effect/sql": 0.49.0
  "@effect/sql-drizzle": 0.48.0
  "@effect/sql-pg": 0.50.0
  effect: 3.19.13

  # Radix UI
  "@radix-ui/react-accordion": 1.2.12
  "@radix-ui/react-alert-dialog": 1.1.15
  "@radix-ui/react-aspect-ratio": 1.1.8
  "@radix-ui/react-avatar": 1.1.11
  "@radix-ui/react-checkbox": 1.3.3
  "@radix-ui/react-collapsible": 1.1.12
  "@radix-ui/react-context-menu": 2.2.16
  "@radix-ui/react-dialog": 1.1.15
  "@radix-ui/react-dropdown-menu": 2.1.16
  "@radix-ui/react-hover-card": 1.1.15
  "@radix-ui/react-label": 2.1.8
  "@radix-ui/react-menubar": 1.1.16
  "@radix-ui/react-navigation-menu": 1.2.14
  "@radix-ui/react-popover": 1.1.15
  "@radix-ui/react-progress": 1.1.8
  "@radix-ui/react-radio-group": 1.3.8
  "@radix-ui/react-scroll-area": 1.2.10
  "@radix-ui/react-select": 2.2.6
  "@radix-ui/react-separator": 1.1.8
  "@radix-ui/react-slider": 1.3.6
  "@radix-ui/react-slot": 1.2.4
  "@radix-ui/react-switch": 1.2.6
  "@radix-ui/react-tabs": 1.1.13
  "@radix-ui/react-toast": 1.2.15
  "@radix-ui/react-toggle": 1.1.10
  "@radix-ui/react-toggle-group": 1.1.11
  "@radix-ui/react-tooltip": 1.2.8

  # React & Next.js
  next: 15.5.9
  react: 19.2.3
  react-dom: 19.2.3
  next-themes: 0.4.6

  # Forms
  "@hookform/resolvers": 5.2.2
  react-hook-form: 7.69.0
  zod: 3.25.76

  # UI Components
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  embla-carousel-react: 8.6.0
  input-otp: 1.4.2
  lucide-react: 0.562.0
  react-day-picker: 9.13.0
  react-resizable-panels: 4.1.0
  recharts: 3.6.0
  sonner: 2.0.7
  vaul: 1.1.2

  # Tailwind
  "@tailwindcss/postcss": 4.1.18
  autoprefixer: 10.4.23
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7

  # Database
  drizzle-orm: 0.45.1
  drizzle-kit: 0.31.8
  postgres: 3.4.7

  # Auth & API
  better-auth: 1.4.9
  openai: 5.8.2
  resend: 4.6.0

  # Utilities
  date-fns: 4.1.0
  multer: 2.0.2
  postcss: 8.5.6
  uuid: 11.1.0

  # Types
  "@types/multer": 2.0.0
  "@types/node": 22.15.21
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@types/uuid": 10.0.0

  # Dev tools
  "@biomejs/biome": 2.0.6
  "@next/env": 15.5.9
  "@typescript/native-preview": 7.0.0-dev.20251230.1
  typescript: 5.9.3
