packages:
  - apps/*
  - packages/*
  - tests/*

catalog:
  '@ai-sdk/gateway': 3.0.22
  '@aws-sdk/client-s3': 3.974.0
  '@aws-sdk/lib-storage': 3.974.0
  '@aws-sdk/s3-request-presigner': 3.974.0
  '@azure/msal-node': 5.0.2
  '@better-auth/oauth-provider': 1.4.17
  '@better-auth/passkey': 1.4.17
  '@better-auth/sso': 1.4.17
  '@better-auth/stripe': 1.4.17
  '@biomejs/biome': 2.3.11
  '@effect/cli': 0.73.1
  '@effect/platform': 0.94.2
  '@effect/platform-bun': 0.87.1
  '@effect/platform-node': 0.104.1
  '@effect/sql': 0.49.0
  '@effect/sql-drizzle': 0.48.0
  '@effect/sql-pg': 0.50.1
  '@effect/vitest': 0.27.0
  '@microsoft/microsoft-graph-client': 3.0.7
  '@microsoft/microsoft-graph-types': 2.43.1
  '@next/env': 16.1.4
  '@notionhq/client': 5.7.0
  '@octokit/graphql': 9.0.3
  '@octokit/oauth-methods': 6.0.2
  '@octokit/types': 16.0.0
  '@playwright/test': 1.58.0
  '@posthog/nextjs-config': 1.8.3
  input-otp: 1.4.2
  radix-ui: 1.4.3
  react-hook-form: 7.71.1
  recharts: 3.7.0
  '@slack/web-api': 7.13.0
  '@slack/webhook': 7.0.6
  '@stripe/stripe-js': 8.6.4
  '@tailwindcss/postcss': 4.1.18
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.2
  '@types/bun': 1.3.6
  '@types/node': 25.0.10
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  '@typescript/native-preview': 7.0.0-dev.20260122.4
  '@upstash/ratelimit': 2.0.8
  '@upstash/redis': 1.36.1
  '@vercel/analytics': 1.6.1
  '@vercel/config': 0.0.26
  '@vercel/microfrontends': 2.2.2
  '@vitejs/plugin-react': 5.1.2
  '@vitest/coverage-v8': 4.0.18
  '@zoom/rivet': 0.4.0
  ai: 6.0.49
  assemblyai: 4.22.1
  autoprefixer: 10.4.23
  bash-tool: 1.3.9
  better-auth: 1.4.17
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  dotenv: 17.2.3
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  effect: 3.19.15
  embla-carousel-react: 8.6.0
  googleapis: 170.1.0
  jsdom: 27.4.0
  knip: 5.82.1
  lefthook: 2.0.15
  lucide-react: 0.563.0
  motion: 12.29.0
  next: 16.1.4
  next-intl: 4.7.0
  next-themes: 0.4.6
  octokit: 5.0.5
  openai: 6.16.0
  postcss: 8.5.6
  postgres: 3.4.8
  posthog-js: 1.335.0
  posthog-node: 5.24.1
  react: 19.2.3
  react-day-picker: 9.13.0
  react-dom: 19.2.3
  react-markdown: 10.1.0
  react-qr-code: 2.0.18
  react-resizable-panels: 4.4.1
  remark-gfm: 4.0.1
  replicate: 1.4.0
  resend: 6.8.0
  server-only: 0.0.1
  sonner: 2.0.7
  streamdown: 2.1.0
  stripe: 20.2.0
  swr: 2.3.8
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7
  tslog: 4.10.2
  tsx: 4.21.0
  turbo: 2.7.5
  twitter-api-v2: 1.29.0
  typescript: 5.9.3
  vaul: 1.1.2
  uuid: 13.0.0
  vitest: 4.0.18
  workflow: 4.0.1-beta.50

catalogMode: strict
