#!/usr/bin/env npx tsx

/**
 * Better Auth Schema Generator
 *
 * Generates the auth.ts schema file from better-auth CLI and adds a header comment.
 * This script should be run whenever better-auth is updated to regenerate the schema.
 *
 * Usage:
 *   pnpm auth:generate
 */

import { execSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import process from "node:process";

const AUTH_SCHEMA_PATH = path.join(process.cwd(), "src/lib/db/schema/auth.ts");
const TEMP_OUTPUT_PATH = path.join(process.cwd(), "temp-auth-schema.ts");

const HEADER_COMMENT = `/**
 * Better Auth Schema - Auto-Generated
 *
 * This file is generated by better-auth CLI and should not be edited manually.
 * To regenerate, run: pnpm auth:generate
 *
 * Tables managed by better-auth:
 * - users: User accounts (core)
 * - sessions: Active user sessions
 * - accounts: OAuth provider connections
 * - verifications: Email/phone verification tokens
 *
 * Organization plugin tables:
 * - organizations: Multi-tenant organizations
 * - members: Organization membership
 * - invitations: Pending organization invites
 *
 * Plugin tables:
 * - twoFactors: Two-factor authentication settings
 * - passkeys: WebAuthn passkey credentials
 * - apikeys: API key authentication
 * - subscriptions: Stripe subscription data (stripe plugin)
 *
 * OAuth Provider tables:
 * - oauthClients: Registered OAuth applications
 * - oauthRefreshTokens: OAuth refresh tokens
 * - oauthAccessTokens: OAuth access tokens
 * - oauthConsents: User OAuth consent records
 *
 * IMPORTANT: Application-specific user data should go in userExtensions table,
 * NOT in the users table. This keeps auth schema clean and makes upgrades easier.
 *
 * @see https://www.better-auth.com/docs/concepts/database
 * @generated
 */

`;

function main() {
  console.log("🔐 Generating better-auth schema...\n");

  try {
    // Run better-auth CLI to generate schema
    console.log("Running better-auth CLI...");
    execSync(`pnpm dlx @better-auth/cli@latest generate --output ${TEMP_OUTPUT_PATH} --yes`, {
      stdio: "inherit",
      cwd: process.cwd(),
    });

    // Read the generated file
    if (!fs.existsSync(TEMP_OUTPUT_PATH)) {
      console.error("❌ CLI did not generate output file");
      process.exit(1);
    }

    let generatedContent = fs.readFileSync(TEMP_OUTPUT_PATH, "utf-8");

    // Fix imports to use local enums file
    generatedContent = generatedContent
      .replace(/from ["']drizzle-orm\/pg-core["']/g, 'from "drizzle-orm/pg-core"')
      .replace(/import \{([^}]+)\} from ["']drizzle-orm\/pg-core["']/, (_match, imports) => {
        // Remove pgEnum from drizzle imports if present since we use our local enums
        const importList = imports.split(",").map((s: string) => s.trim());
        const filteredImports = importList.filter((s: string) => s !== "pgEnum");
        return `import { ${filteredImports.join(", ")} } from "drizzle-orm/pg-core"`;
      });

    // Remove relations from the generated file since we define them in relations.ts
    // This prevents duplicate export conflicts when both auth.ts and relations.ts are exported from index.ts
    // Remove the relations import
    generatedContent = generatedContent.replace(/import \{ relations \} from ["']drizzle-orm["'];\n?/g, "");
    // Remove all relation definitions (export const xxxRelations = relations(...))
    generatedContent = generatedContent.replace(/export const \w+Relations = relations\([^;]+\);\n?\n?/g, "");

    // Add header comment
    const finalContent = HEADER_COMMENT + generatedContent;

    // Write to the schema file
    fs.writeFileSync(AUTH_SCHEMA_PATH, finalContent);

    // Clean up temp file
    fs.unlinkSync(TEMP_OUTPUT_PATH);

    console.log("\n✅ Auth schema generated successfully!");
    console.log(`   Output: ${AUTH_SCHEMA_PATH}`);
  } catch (error) {
    // Clean up temp file if it exists
    if (fs.existsSync(TEMP_OUTPUT_PATH)) {
      fs.unlinkSync(TEMP_OUTPUT_PATH);
    }

    if (error instanceof Error) {
      console.error("\n❌ Failed to generate auth schema:", error.message);
      console.log("\n📝 Manual regeneration steps:");
      console.log("   1. Fix any better-auth configuration issues");
      console.log("   2. Run: pnpm dlx @better-auth/cli@latest generate");
      console.log("   3. Move output to: src/lib/db/schema/auth.ts");
      console.log("   4. Add the header comment from this script");
    }
    process.exit(1);
  }
}

main();
